# Generated by Django 5.1.7 on 2025-04-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='subscription_status',
            field=models.CharField(default='Trial', max_length=10),
        ),
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(auto_now_add=True),
        ),
    ]
