# Generated by Django 5.1.7 on 2025-04-08 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0002_lender_subscription_status_alter_lender_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 5, 8)),
        ),
    ]
