# Generated by Django 5.1.7 on 2025-04-11 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0003_alter_lender_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='time_left',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 5, 11)),
        ),
    ]
