# Generated by Django 5.1.7 on 2025-04-12 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0004_lender_time_left_alter_lender_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 5, 12)),
        ),
        migrations.AlterField(
            model_name='lender',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
