# Generated by Django 5.1.7 on 2025-04-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0005_alter_lender_expiry_alter_lender_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
