# Generated by Django 5.1.7 on 2025-04-14 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0006_alter_borrower_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggreements',
            name='aggreement',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='asset_photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='proof',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 5, 14)),
        ),
    ]
