# Generated by Django 5.1.7 on 2025-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0007_alter_aggreements_aggreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
