# Generated by Django 5.1.7 on 2025-04-14 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0008_loans_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
