# Generated by Django 5.1.7 on 2025-04-15 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0010_alter_repayment_percentage_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 5, 15)),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='percentage_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
