# Generated by Django 5.1.7 on 2025-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0011_alter_lender_expiry_alter_repayment_percentage_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='asset_name',
            field=models.CharField(default='Not Added', max_length=100),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='description',
            field=models.TextField(default='Not Added'),
        ),
    ]
