# Generated by Django 5.1.7 on 2025-04-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0012_alter_collateral_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggreements',
            name='aggreement',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aggreements',
            name='borrower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.borrower'),
        ),
        migrations.AlterField(
            model_name='aggreements',
            name='lender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.lender'),
        ),
        migrations.AlterField(
            model_name='aggreements',
            name='loan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.loans'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='aggr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.aggreements'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='asset_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='borrower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.borrower'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='lender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.lender'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='loan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.loans'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='proof',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='borrower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.borrower'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='lender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.lender'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='loan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kimtech.loans'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='percentage_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
