# Generated by Django 5.1.7 on 2025-04-16 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0013_alter_aggreements_aggreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 5, 16)),
        ),
    ]
