# Generated by Django 5.1.7 on 2025-04-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0014_alter_lender_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggreements',
            name='loan_date',
        ),
    ]
