# Generated by Django 5.1.7 on 2025-04-22 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0015_remove_aggreements_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='logo',
            field=models.ImageField(default='/static/images/logo-placeholder.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 5, 22)),
        ),
    ]
