# Generated by Django 5.1.7 on 2025-04-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0016_borrower_logo_alter_lender_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='logo',
        ),
        migrations.AddField(
            model_name='lender',
            name='logo',
            field=models.ImageField(default='/static/images/logo-placeholder.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='photo',
            field=models.ImageField(default='/static/images/icon.png', upload_to='images/'),
        ),
    ]
