# Generated by Django 5.2 on 2025-05-07 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0017_remove_borrower_logo_lender_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 6, 6)),
        ),
    ]
