# Generated by Django 5.2 on 2025-05-23 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0018_alter_lender_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repayment',
            name='bal',
        ),
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 6, 22)),
        ),
    ]
