# Generated by Django 5.2 on 2025-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0019_remove_repayment_bal_alter_lender_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='bal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
