# Generated by Django 5.2 on 2025-05-28 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0020_repayment_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='comments',
            field=models.TextField(default='Not Added'),
        ),
        migrations.AddField(
            model_name='loans',
            name='effectDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loans',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loans',
            name='startDate',
            field=models.DateField(default=datetime.date(2025, 5, 28)),
        ),
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 6, 27)),
        ),
    ]
