# Generated by Django 5.2 on 2025-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0021_loans_comments_loans_effectday_loans_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='buz',
            field=models.CharField(default='Not Added', max_length=20),
        ),
        migrations.AddField(
            model_name='borrower',
            name='buzloc',
            field=models.CharField(default='Not Added', max_length=20),
        ),
        migrations.AddField(
            model_name='borrower',
            name='chair',
            field=models.CharField(default='Not Added', max_length=20),
        ),
        migrations.AddField(
            model_name='borrower',
            name='chairTel',
            field=models.CharField(default='Not Added', max_length=20),
        ),
        migrations.AddField(
            model_name='borrower',
            name='nextOfKin',
            field=models.CharField(default='Not Added', max_length=20),
        ),
        migrations.AddField(
            model_name='borrower',
            name='nextOfKinTel',
            field=models.CharField(default='Not Added', max_length=20),
        ),
        migrations.AddField(
            model_name='loans',
            name='dailyPay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='pin',
            field=models.CharField(max_length=20),
        ),
    ]
