# Generated by Django 5.2 on 2025-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0022_borrower_buz_borrower_buzloc_borrower_chair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
