# Generated by Django 5.2 on 2025-05-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0023_alter_loans_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='photo',
            field=models.ImageField(default='/static/images/blankPerson.jpeg', upload_to='images/'),
        ),
    ]
