# Generated by Django 5.2 on 2025-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0024_alter_borrower_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='penaltyAmountAdded',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
