# Generated by Django 5.2 on 2025-05-29 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0025_loans_penaltyamountadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 6, 28)),
        ),
        migrations.AlterField(
            model_name='loans',
            name='balance',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loans',
            name='interest_rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loans',
            name='penaltyAmountAdded',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loans',
            name='total_amm',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='bal',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='percentage_paid',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
