# Generated by Django 5.2 on 2025-05-31 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kimtech', '0026_alter_lender_expiry_alter_loans_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('amm', models.DecimalField(decimal_places=6, default=0.0, max_digits=16)),
                ('txnID', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lender',
            name='expiry',
            field=models.DateField(default=datetime.date(2025, 6, 30)),
        ),
    ]
